### ISSUE TITLE
Not able to run the script

### ISSUE THREAD

**Issue by jagmeetbhinder** [carlniger/acitool#26]
I am trying to run your script and getting below error. Can you please assist?

 python main.py 
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import acipdt
  File "/home/scripts/aci-scripts/acipdt/acipdt/acipdt.py", line 46
    templateVars = {**required_args, **optional_args}
                     ^
SyntaxError: invalid syntax

**Comment by jagmeetbhinder** [comment]
Never mind, I need to use python3. Thanks for such a great work. You are awesome
